[env:esp32-c6]
platform = espressif32
board = esp32-c6-devkitc-1
framework = arduino

build_flags =
    -D ARDUINO_RUNNING_CORE=1
    -D CORE_DEBUG_LEVEL=1
    -D CONFIG_ESP32C6_DEFAULT_CPU_FREQ_MHZ=160

monitor_speed = 115200

lib_deps =
    https://github.com/Bodmer/TFT_eSPI.git
    SD
